# Generated by Django 5.0 on 2024-01-07 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_alter_post_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_at",)},
        ),
    ]
