# Generated by Django 5.0 on 2024-01-11 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0006_alter_comment_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
    ]
