# Generated by Django 5.0 on 2024-01-12 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_user_posts_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friend_suggestions",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
