# Generated by Django 5.0 on 2024-01-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("friend_request", "Friend Request"),
                    ("friend_accept", "Friend Accept"),
                    ("friend_reject", "Friend Reject"),
                ],
                max_length=20,
            ),
        ),
    ]
